tablec{1} = {'Spatial Frequency (cpd)', 0.04, .04, 0.04;...
    'Temporal Frequency (cps)', 3, 1, 3;...
    'Contrast (start,end,numsteps)', 1, 1, 1;...
    'Orientation', 0, 180, 180;...
    'Timing (delay,duration,wait) (s)', 1, 2, 1;...
    'Blank', 0, [], [];
    'Randomize', 0, [], [];...
    'Interleave', 0, [], [];...
    'Repeats', 0, [], [];...
    'Initialization Screen (s)', 5, [],[]};
stimTypec{1} = 'Full-field Grating';